/********************************************************
 * Copyright Regione Piemonte - 2021					*
 * SPDX-License-Identifier: EUPL-1.2-or-later			*
 ********************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.22 at 12:20:01 PM CEST 
//


package it.csi.pslp.pslorch.business.integration.dto.sms.consultazione.richiesta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "username",
    "password",
    "codiceprogetto",
    "telefono",
    "datainviostart",
    "datainvioend",
    "note",
    "stato"
})
@XmlRootElement(name = "CONSULTAZIONE_SMS")
public class CONSULTAZIONESMS {

    @XmlElement(name = "USERNAME", required = true)
    protected String username;
    @XmlElement(name = "PASSWORD", required = true)
    protected String password;
    @XmlElement(name = "CODICE_PROGETTO", required = true)
    protected String codiceprogetto;
    @XmlElement(name = "TELEFONO", required = true)
    protected String telefono;
    @XmlElement(name = "DATA_INVIO_START", required = true)
    protected String datainviostart;
    @XmlElement(name = "DATA_INVIO_END", required = true)
    protected String datainvioend;
    @XmlElement(name = "NOTE", required = true)
    protected String note;
    @XmlElement(name = "STATO", required = true)
    protected String stato;

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSERNAME() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSERNAME(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPASSWORD() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPASSWORD(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the codiceprogetto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODICEPROGETTO() {
        return codiceprogetto;
    }

    /**
     * Sets the value of the codiceprogetto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODICEPROGETTO(String value) {
        this.codiceprogetto = value;
    }

    /**
     * Gets the value of the telefono property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTELEFONO() {
        return telefono;
    }

    /**
     * Sets the value of the telefono property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTELEFONO(String value) {
        this.telefono = value;
    }

    /**
     * Gets the value of the datainviostart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDATAINVIOSTART() {
        return datainviostart;
    }

    /**
     * Sets the value of the datainviostart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDATAINVIOSTART(String value) {
        this.datainviostart = value;
    }

    /**
     * Gets the value of the datainvioend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDATAINVIOEND() {
        return datainvioend;
    }

    /**
     * Sets the value of the datainvioend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDATAINVIOEND(String value) {
        this.datainvioend = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNOTE() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNOTE(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the stato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATO() {
        return stato;
    }

    /**
     * Sets the value of the stato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATO(String value) {
        this.stato = value;
    }

}
